#!/bin/sh

set -e

# summary of how this script can be called:
#
#   * <postrm> `remove'
#   * <postrm> `purge'
#   * <old-postrm> `upgrade' <new-version>
#   * <disappearer's-postrm> `disappear' <overwriter> <overwriter-version>
#   * <new-postrm> `failed-upgrade' <old-version> <new-version>
#   * <new-postrm> `abort-install'
#   * <new-postrm> `abort-install' <old-version> <new-version>
#   * <new-postrm> `abort-upgrade' <old-version> <new-version>
#
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

remove_config_from_template() {
    local config="$1"
    local template="$2"
    local firstver="$3"

    if [ "$4" != "--" ]; then
        echo "remove_config_from_template called with the wrong number of arguments" >&2
        return 1
    fi
    for _ in $(seq 1 4); do
        shift
    done

    if [ "$1" = "remove" ] && [ -e "$config" ]; then
        # When removing the package, move the configuration file to the side
        # so that the daemon no longer sees it, but we can still restore it
        # at a later time if the package is reinstalled
        mv -f "$config" "$config.dpkg-backup"
        return 0
    fi

    if [ "$1" = "purge" ]; then
        # When purging the package, remove all traces of the configuration
        rm -f "$config" "$config.dpkg-backup"
        return 0
    fi
}

case "$1" in
    remove)
        remove_config_from_template \
            "/etc/libvirt/qemu/networks/default.xml" \
            "/usr/share/libvirt/networks/default.xml" \
            "6.9.0-2~" \
            -- \
            "$@"

        if [ -L /etc/dnsmasq.d/libvirt-daemon ]; then
            echo "Removing libvirt-daemon dnsmasq configuration"
            rm -f /etc/dnsmasq.d/libvirt-daemon || true

            # Try to restart a potential system wide dnsmasq
            invoke-rc.d dnsmasq restart || true
        fi


        # Trigger daemon restart after removing configuration files
        dpkg-trigger libvirt-restart-libvirtd

        # Remove the link set up by postinst
        rm -f /etc/libvirt/qemu/networks/autostart/default.xml
    ;;

    purge)
        # a running libvirt-dnsmasq will break these removals
        # yet the lifecycle of the network is non-related to the pkg purge
        # Therefore ignore errors on these removals, better leave a user than break
        if getent group libvirt-dnsmasq >/dev/null; then
            delgroup libvirt-dnsmasq --system >/dev/null || true
        fi
        if getent passwd libvirt-dnsmasq >/dev/null; then
            deluser libvirt-dnsmasq --system >/dev/null || true
        fi
    ;;

    upgrade|disappear|failed-upgrade|abort-install|abort-upgrade)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installdeb/13.28ubuntu1
dpkg-maintscript-helper dir_to_symlink /usr/share/doc/libvirt-daemon-config-network libvirt-common 10.6.0-2\~ -- "$@"
# End automatically added section


exit 0
