#!/bin/sh

set -e

# summary of how this script can be called:
#
#   * <postrm> `remove'
#   * <postrm> `purge'
#   * <old-postrm> `upgrade' <new-version>
#   * <disappearer's-postrm> `disappear' <overwriter> <overwriter-version>
#   * <new-postrm> `failed-upgrade' <old-version> <new-version>
#   * <new-postrm> `abort-install'
#   * <new-postrm> `abort-install' <old-version> <new-version>
#   * <new-postrm> `abort-upgrade' <old-version> <new-version>
#
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

delete_protective_diversion() {
    local usrfile="$1"
    local firstver="$2"

    if [ "$3" != "--" ]; then
        echo "delete_protective_diversion called with the wrong number of arguments" >&2
        return 1
    fi
    for _ in $(seq 1 3); do
        shift
    done

    # If the diversion doesn't exist there's nothing to clean up
    if [ -z "$(dpkg-divert --list "$usrfile")" ]; then
        return 0
    fi

    dpkg-divert \
        --no-rename \
        --divert "$usrfile.usr-is-merged" \
        --remove "$usrfile"
}

DAEMON_UNITS="
    libvirtd-admin.socket
    libvirtd-ro.socket
    libvirtd-tcp.socket
    libvirtd-tls.socket
    libvirtd.service
    libvirtd.socket
"

case "$1" in
    failed-upgrade|abort-install|abort-upgrade)
        for unit in $DAEMON_UNITS; do
            delete_protective_diversion \
                "/lib/systemd/system/$unit" \
                "10.6.0-3~" \
                -- \
                "$@"
        done
    ;;

    remove|purge|upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installinit/13.28ubuntu1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/libvirtd" ] ; then
	chmod -x "/etc/init.d/libvirtd" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d libvirtd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.28ubuntu1
dpkg-maintscript-helper dir_to_symlink /usr/share/doc/libvirt-daemon libvirt-common 10.6.0-2\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.28ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.28ubuntu1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'libvirtd-admin.socket' 'libvirtd-ro.socket' 'libvirtd.socket' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.28ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.28ubuntu1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'libvirtd.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_apparmor/5.0.0~beta1-0ubuntu2
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.sbin.libvirtd" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.sbin.libvirtd" || true
    rm -f "/etc/apparmor.d/force-complain/usr.sbin.libvirtd" || true
    rm -f "/etc/apparmor.d/local/usr.sbin.libvirtd" || true
    rm -f /var/cache/apparmor/*/"usr.sbin.libvirtd" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section


exit 0
