#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.28ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'libvirtd-admin.socket' 'libvirtd-ro.socket' 'libvirtd.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.28ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'libvirtd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.28ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/libvirtd" ] ; then
	invoke-rc.d --skip-systemd-native libvirtd stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.28ubuntu1
dpkg-maintscript-helper dir_to_symlink /usr/share/doc/libvirt-daemon libvirt-common 10.6.0-2\~ -- "$@"
# End automatically added section
