#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.28ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'virtlogd-admin.socket' 'virtlogd.service' 'virtlogd.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.28ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/virtlogd" ] ; then
	invoke-rc.d --skip-systemd-native virtlogd stop || exit 1
fi
# End automatically added section
