#!/bin/sh

set -e

# begin-remove-after: released:26.04
# Keep existing configuration files (some created by maintainer scripts from
# templates) in (old < 11.0.0-2ubuntu8) libvirt-daemon-driver-qemu.postinst.
# This logic moved into libvirt-daemon-config-network, but we want to keep the
# original files. (LP: #2107448)
if [ "$1" = install ] || [ "$1" = upgrade ]; then
    # Not owned by the pkg, postrm might call remove_config_from_template which would leave a .dpkg-backup
    # Priority #1 - if there still is a /etc/libvirt/qemu/networks/default.xml - keep it untouched
    # Priority #2 - if not #1, but there is a /etc/libvirt/qemu/networks/default.xml.dpkg-backup restore it as active config
    # Priority #3 - if neither of the above apply, it means next install will do a fresh create_config_from_template in postinst
    netconf="/etc/libvirt/qemu/networks/default.xml"
    if [ ! -e "${netconf}" ]; then
        if [ -e "${netconf}.dpkg-backup" ]; then
            cp "${netconf}.dpkg-backup" "${netconf}"
        fi
    fi
    # Owned by the pkg, if it was modified dpkg would retain it as .dpkg-upgrade
    dpkg-divert --rename --divert /etc/dnsmasq.d-available/libvirt-daemon.dpkg-upgrade --add /etc/dnsmasq.d-available/libvirt-daemon
fi
# end-remove-after

# Automatically added by dh_installdeb/13.28ubuntu1
dpkg-maintscript-helper dir_to_symlink /usr/share/doc/libvirt-daemon-config-network libvirt-common 10.6.0-2\~ -- "$@"
# End automatically added section

