#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.28ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'qemu-guest-agent.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.28ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/qemu-guest-agent" ] ; then
	invoke-rc.d --skip-systemd-native qemu-guest-agent stop || exit 1
fi
# End automatically added section
