#!/bin/sh

set -e

# summary of how this script can be called:
#
#   * <postinst> `configure' <most-recently-configured-version>
#   * <old-postinst> `abort-upgrade' <new-version>
#   * <conflictor's-postinst> `abort-remove' `in-favour' <package> <new-version>
#   * <postinst> `abort-remove'
#   * <deconfigured's-postinst> `abort-deconfigure' `in-favour' <failed-install-package>
#     <version> `removing' <conflicting-package> <version>
#
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package



case "$1" in
    configure)
        # Load the msr module right away to properly detect CPU features from
        # Model Specific Registers.
        # At boot, the module is loaded automatically by modules-load.
        MSR_MODULES_LOAD_FILE="/etc/modules-load.d/libvirt-msr.conf"
        if [ -z "${DPKG_ROOT}" ] && [ -d /run/systemd/system ]; then
            if [ -x /usr/lib/systemd/systemd-modules-load ]; then
                /usr/lib/systemd/systemd-modules-load ${MSR_MODULES_LOAD_FILE} || true
            fi
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
