#!/bin/sh
set -e
### added by qemu/debian/gen-module-upgrade.sh:
case $1 in
(upgrade|deconfigure)
  # only save if qemu-system-* or kvm process running
  # can also check version of the running processes
  if ps -e -o comm | grep -E -q '^(qemu-system-|kvm$)'; then
    echo "qemu-block-extra: qemu process(es) running, saving block modules in /run/qemu/Debian_1_10.2.1+ds-1ubuntu1..."
    mkdir -p -m 0755 /run/qemu/Debian_1_10.2.1+ds-1ubuntu1
    ( cd /usr/lib/x86_64-linux-gnu/qemu/; cp -p -n -t /run/qemu/Debian_1_10.2.1+ds-1ubuntu1/ block-curl.so block-dmg-bz2.so block-iscsi.so block-nfs.so block-rbd.so block-ssh.so )
    > /run/qemu/Debian_1_10.2.1+ds-1ubuntu1/.savemoddir; chmod 0744 /run/qemu/Debian_1_10.2.1+ds-1ubuntu1/.savemoddir
    if [ ! -x /run/qemu/Debian_1_10.2.1+ds-1ubuntu1/.savemoddir ]; then # mounted noexec?
       mountpoint -q /run/qemu/Debian_1_10.2.1+ds-1ubuntu1 || mount --bind /run/qemu/Debian_1_10.2.1+ds-1ubuntu1 /run/qemu/Debian_1_10.2.1+ds-1ubuntu1
       mount -o remount,exec /run/qemu/Debian_1_10.2.1+ds-1ubuntu1
    fi
  fi
  ;;
esac
### end added section
